// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure

export interface Database {
  public: {
    Tables: {
      emails: {
        Row: {
          id: string;
          user_id: string;
          gmail_id: string;
          subject: string;
          sender: string;
          recipients: string[];
          body: string;
          importance_score: number;
          category: string;
          requires_followup: boolean;
          processed_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gmail_id: string;
          subject: string;
          sender: string;
          recipients: string[];
          body: string;
          importance_score?: number;
          category?: string;
          requires_followup?: boolean;
          processed_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gmail_id?: string;
          subject?: string;
          sender?: string;
          recipients?: string[];
          body?: string;
          importance_score?: number;
          category?: string;
          requires_followup?: boolean;
          processed_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      threads: {
        Row: {
          id: string;
          gmail_thread_id: string;
          user_id: string;
          subject: string;
          participants: string[];
          last_activity: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          gmail_thread_id: string;
          user_id: string;
          subject: string;
          participants: string[];
          last_activity: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          gmail_thread_id?: string;
          user_id?: string;
          subject?: string;
          participants?: string[];
          last_activity?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          email_id: string;
          user_id: string;
          title: string;
          description: string;
          status: string;
          priority: string;
          due_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email_id: string;
          user_id: string;
          title: string;
          description: string;
          status?: string;
          priority?: string;
          due_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email_id?: string;
          user_id?: string;
          title?: string;
          description?: string;
          status?: string;
          priority?: string;
          due_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_preferences: {
        Row: {
          id: string;
          user_id: string;
          category_weights: Record<string, number>;
          importance_thresholds: Record<string, number>;
          notification_settings: Record<string, any>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          category_weights?: Record<string, number>;
          importance_thresholds?: Record<string, number>;
          notification_settings?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          category_weights?: Record<string, number>;
          importance_thresholds?: Record<string, number>;
          notification_settings?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
} 